from .account import CommunityAccountModule
from .acm import ACMModule
from .admin import CommunityModeratorModule
from .blogs import CommunityBlogsModule
from .chats import CommunityChatsModule
from .comments import CommunityCommentsModule
from .notifications import CommunityNotificationsModule
from .other import CommunityOtherModule
from .sticker import CommunityStickersModule
from .users import CommunityUsersModule